global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app1-python'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['app1:5000']

  - job_name: 'app2-nodejs'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['app2:3000']

  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status